var config = {
  'apiUrl': 'https://bhtcookie.blob.core.windows.net/bhtguild/',
  'rankings': 'guildrankings.json',
  'guild': 'guild/{{guildId}}.json',
  'battle': 'guild/{{guildId}}/{{battleId}}.json',
  // @todo: Go by commit or by master branch?
  //'dataUrl': 'https://raw.githubusercontent.com/WotVFarmCalculator/wotvfarmcalculator.github.io/21fd8434f6a3fe8af2a1352f9f83ff9ad64fa8e8/',
  'dataUrl': 'https://raw.githubusercontent.com/shalzuth/wotv-ffbe-dump/master/',
  'validActions': [
    'rankings',
    'guild',
    'battle'
  ],
  'validLeagues': {
    'legend': 'Legend',
    'master1': 'Master I',
    'master2': 'Master II',
    'master3': 'Master III',
    'champion1': 'Champion I',
    'champion2': 'Champion II',
    'champion3': 'Champion III',
    'diamond1': 'Diamond I',
    'diamond2': 'Diamond II',
    'diamond3': 'Diamond III',
    'platinum1': 'Platinum I',
    'platinum2': 'Platinum II',
    'platinum3': 'Platinum III',
    'gold1': 'Gold I',
    'gold2': 'Gold II',
    'gold3': 'Gold III',
    'silver1': 'Silver I',
    'silver2': 'Silver II',
    'silver3': 'Silver III',
    'bronze1': 'Bronze I',
    'bronze2': 'Bronze II',
    'bronze3': 'Bronze III',
  },
  'darkModeKey': 'guildDarkMode',
};
